{% set version = "2.1.8" %}
{% set sha256 = "ad61bc25deadb535b047684d06f3654c001d9415e1971e51c9c20f5b510076e9" %}

package:
  name: gitpython
  version: {{ version }}

source:
  fn: GitPython-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip

  run:
    - python
    - gitdb2

test:
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python Git Library'
  doc_url:  http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
